name: leave_management_system
description: A smart leave management system built with Flutter and Supabase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.0.9
  
  # Notifications
  flutter_local_notifications: ^19.4.2
  
  # Navigation
  go_router: ^16.2.2
  
  # HTTP & JSON
  http: ^1.2.2
  json_annotation: ^4.9.0
  
  # File handling
  file_picker: ^10.3.3
  image_picker: ^1.1.2
  
  # Utils
  uuid: ^4.5.0
  shared_preferences: ^2.2.2
  
  # UI Enhancements
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - .env